[POOL]
algo   = " --scrypt"
option = " --gridseed-options=baud=115200,freq=800,chips=40,modules=1,usefifo=0,btc=0"
host = " --url=stratum+tcp://us.litecoinpool.org:3333"
userPassWorker  = " --userpass=yarichin.1:1 "
usbDevice = "lsusb | grep STM | cut -c5-7,15-18"
usbDeviceCount = "lsusb | grep STM | wc -l"

#3 usbDevice debug
#production STM, development ID